# Generated by Django 4.2.2 on 2023-07-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('in_house', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HackerNewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('news_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.hackernewsitem', to_field='item_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.hackernewscomment')),
            ],
        ),
    ]
